[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  'openzeppelin-contracts-v3.4.2/contracts=lib/openzeppelin-contracts-v3.4.2/contracts',
  'openzeppelin-contracts-v4.7.3/contracts=lib/openzeppelin-contracts-v4.7.3/contracts',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
